# # # # # # # #
#   K i k o   #
# # # # # # # #

# Basic
name:               "Swift"
subname:             ".tnantoka.com"

# URL
baseurl:            ""
#baseurl:            "" #For Root Domain
permalink:          /:year/:month/:day/:title.html

# Markdown
markdown:           rdiscount

# Navigation
nav:
  - name:           "About"
    href:           "/about"
  - name:           "Links"
    href:           "/links"
  - name:           "25 Days"
    href:           "/25days"

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
